server:
  port: 4000

spring:
  datasource:
    mongodb:
      host: mongo_db
      port: 27017
      database: admin
      username: root
      password: dev00
    redis:
      host: redis_db
      port: 6379
    database:
      master:
        jdbc-url: jdbc:mariadb://maria_db:3306/users?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: users
        password: dev00_users
        driver-class-name: org.mariadb.jdbc.Driver
      slave:
        jdbc-url: jdbc:mariadb://maria_db:3306/users?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: users_slave
        password: dev00_users
        driver-class-name: org.mariadb.jdbc.Driver
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MariaDBDialect
            format_sql: true
            use_sql_comments: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: com.demo.project.worker.group
      # consumer의 나머지 설정은 kafkaConfig 파일 참고
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      profile-view: "com.demo.project.profile.view.topic"
      profile-view-dql: "com.demo.project.profile.view.topic.dlq"
      point-save: "com.demo.project.point.save.topic"
      point-save-dql: "com.demo.project.point.save.topic.dlq"
    admin:
      auto-create: true
    properties:
      allow.auto.create.topics: true
