server:
  port: 3002


# database
spring:
  datasource:
    master:
      jdbc-url: jdbc:mariadb://localhost:3307/products?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: products
      password: dev00_products
      driver-class-name: org.mariadb.jdbc.Driver
    slave:
      jdbc-url: jdbc:mariadb://localhost:3307/products?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: products_slave
      password: dev00_products
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true



logging.level:
  org.hibernate.SQL:  # SQL query
  org.hibernate.type : trace # SQL query parameters
