server:
  port: 8000

spring:
  datasource:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: dev00
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

externals:
  # apis - 각 MSA API 정의
  apis:
    api-network:
      payments:
        host: http://localhost:8002
        version: /v1
        uris:
          payments:
            resource: /payments # 포인트 정보
            api-confirm: /confirm # 결제 확인
    core-network: # cores 속한 MSA API 정의
      users:
        host: http://localhost:3001
        version: /v1
        uris:
          members:
            resource: /members # 회원 정보
      products:
        host: http://localhost:3002
        version: /v1
        uris:
          points:
            resource: /points # 포인트 정보


